name: Hellow World
on: [push, workflow_dispatch]
jobs:
  hello-job:
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted, Windows, X64]
    runs-on: ${{matrix.os}}
    steps:
    - name: Echo text
      run: echo "Hello, world!"