name: Testing Self Hosted Runner
on: 
  workflow_dispatch:

jobs:
  testing-job:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Echo Text on cmd
        shell: cmd 
        # It enable this step to bypasses PowerShell and uses Command Prompt instead 
        # Reason -Execution Policy restricts runnig PowerShell Scripts in windows
        run: |
          echo 'testing.. Self Hosted runner'
          echo 'running..'
          echo 'status: OK'

      - name: Echo Text but on Powershell #By Default command will run inside powershell script
        run: |
          echo 'testing.. Self Hosted runner on PS'
          echo 'running.. on powershell'
          echo 'status: OK on powersshell'
          
