name: Testing Self Hosted Runner
on: 
  workflow_dispatch:

jobs:
  testing-job:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Echo Text
        shell: cmd 
        # It enable this step to bypasses PowerShell and uses Command Prompt instead 
        # Reason -Execution Policy restricts runnig PowerShell Scripts in windows
        run: |
          echo 'testing.. Self Hosted runner'
          echo 'running..'
          echo 'status: OK'
          
          
