name: Testing Self Hosted Runner
on: 
  workflow_dispatch:

jobs:
  testing-job:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - name: Echo Text
        shell: cmd
        run: |
          echo 'testing.. Self Hosted runner'
          echo 'running..'
          echo 'status: OK'
          
          
